export const translate = new Map([
  ['name', 'Название'],
  ['fio', 'ФИО'],
  ['mark', 'Марка'],
  ['color', 'Цвет'],
  ['capacity', 'Объем двигателя л.'],
  ['mileage', 'Пробег км./ч.'],
  ['number', 'Номер'],
  ['transmission', 'Коробка передач'],
  ['year', 'Год'],
  ['amount', 'Мощность двигателя л.с.'],
  ['license', 'Номер лицензии'],
  ['nationality', 'Национальность'],
  ['passport', 'Пасспорт'],
  ['birthday', 'День рождения'],
  ['birthcity', 'Город рождения'],
]);